### ISSUE TITLE
Non-RL task

### ISSUE THREAD

**Issue by rahimentezari** [google-research/rl-reliability-metrics#2]
Thanks for releasing the code.
I wonder how we can use your code for Non-RL tasks? Let's say a conventional classification task on CIFAR 100.

**Comment by get-playrooms** [comment]
Hi, apologies for the delayed response. Yes, you can absolutely use these metrics for non-RL tasks! They are targeted towards RL because that is where we often see these issues of non-reliability in training and in deployment. However, if you have a situation in which you expect to see / wish to measure the same kinds of reliability, you can absolutely use these measures there as well. Using your CIFAR 100 classification example, you might wish to measure reliability across different hyperparameters, reliability across different random seeds, etc.
- Stephanie

**Comment by scychan** [comment]
Hi, apologies for the delayed response. Yes, you can absolutely use these metrics for non-RL tasks! They are targeted towards RL because that is where we often see these issues of non-reliability in training and in deployment. However, if you have a situation in which you expect to see / wish to measure the same kinds of reliability, you can absolutely use these measures there as well. Using your CIFAR 100 classification example, you might wish to measure reliability across different hyperparameters, reliability across different random seeds, etc.

-- Stephanie
